#import "../../../users/_gql/fragments/UserRelationshipFragment.gql"
#import "../../../blogposts/_gql/fragments/BlogPostFragment.gql"
#import "./CommentRelationshipFragment.gql"

fragment Comment on Comment {
  __typename
  id
  user_id
  commentable_type
  commentable_id
  comments_count
  has_commented
  is_updated
  content
  commentable {
    ... on BlogPost {
      ...BlogPost
    }
    ... on Comment {
      ...CommentRelationship
    }
  }
  user {
    ...UserRelationship
  }
  comments {
    ...CommentRelationship
  }
  created_at
  updated_at
}
