#import "../../../users/_gql/fragments/UserRelationshipFragment.gql"

fragment CommentRelationship on Comment {
  __typename
  id
  user_id
  content
  commentable_id
  commentable_type
  created_at
  updated_at
  user {
    ...UserRelationship
  }
}
