#import '../../../blogposts/_gql/fragments/BlogPostFragment.gql'

fragment User on User {
  __typename
  id
  role_id
  name
  email
  role
  blogPosts {
    ...BlogPost
  }
  comments {
    id
  }
  created_at
  updated_at
}
