#import "../fragments/BlogPostFragment.gql"

query BlogPosts(
  $orderBy: [OrderByClause!]
  $first: Int!
  $page: Int!
  $title: String
) {
  blogPosts(orderBy: $orderBy, first: $first, page: $page, title: $title) {
    data {
      ...BlogPost
    }
    paginatorInfo {
      currentPage
      lastPage
    }
  }
}
