#import "../../../users/_gql/fragments/UserRelationshipFragment.gql"

fragment BlogPost on BlogPost {
  id
  title
  slug
  description
  content
  user {
    ...UserRelationship
  }
  created_at
  updated_at
}
