#import "../../../users/_gql/fragments/UserRelationshipFragment.gql"
#import "../../../comments/_gql/fragments/CommentRelationshipFragment.gql"

fragment BlogPost on BlogPost {
  __typename
  id
  title
  slug
  is_updated
  comments_count
  created_at
  updated_at
  passage
  content
  user {
    ...UserRelationship
  }
  comments {
    ...CommentRelationship
  }
}
