#import "../../../users/_gql/fragments/UserRelationshipFragment.gql"
#import "../../../comments/_gql/fragments/CommentRelationshipFragment.gql"

fragment BlogPost on BlogPost {
  __typename
  id
  title
  slug
  description
  content
  is_updated
  comments_count
  user {
    ...UserRelationship
  }
  comments {
    ...CommentRelationship
  }
  created_at
  updated_at
}
