#import "../fragments/CommentFragment.gql"

query AllComments($orderBy: [OrderByClause!], $first: Int!, $page: Int!) {
  allComments(orderBy: $orderBy, first: $first, page: $page) {
    data {
      ...Comment
    }
    paginatorInfo {
      currentPage
      lastPage
    }
  }
}
