#import "../fragments/CommentFragment.gql"

query AllComments(
  $orderBy: [OrderByClause!]
  $first: Int!
  $page: Int!
  $id: String
) {
  allComments(orderBy: $orderBy, first: $first, page: $page, id: $id) {
    data {
      ...Comment
    }
    paginatorInfo {
      currentPage
      lastPage
    }
  }
}
